# fly.toml app configuration file generated for aiden-frontend on 2025-04-07T23:15:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aiden'
primary_region = 'fra'

[build]
  builder = "heroku/buildpacks:20"  # wird ignoriert bei Docker/Next, aber harmless

[env]
  NODE_ENV = "production"

[deploy]
  release_command = "npm run build"
  
[experimental]
  auto_rollback = true

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
